feat: add unit tests
DocPlanner/helm-repo-updater pull request #5
Opened 2021-12-27 16:23 UTC by xoanmm

2022-01-03 07:44 UTC, alv91 approved these changes

2022-01-03 08:32 UTC, JorTurFer requested changes
In general, LGTM.
Only small nits

2022-01-10 14:12 UTC, patrykwozinski reviewed
Thanks @xoanmm! I reviewed `.go` files and left some minor questions/suggestions/comments. Feel free to ignore them if something is not valid, I'm not an expert of Go nor this context of the HelmRepoUpdater. No changes requested, only comments-like things.

2022-01-12 14:57 UTC, patrykwozinski approved these changes

2022-01-12 15:16 UTC, merged